[package]
name = "_matrix_rs"
version = "0.1.0"
edition = "2021"

[package.metadata.maturin]
name = "mikesh._matrix_rs"

[lib]
name       = "_matrix_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.18.0", features = ["extension-module"] }
